module.exports = {
  apps: [
    {
      name: "satufile",
      script: "./satufile",
      args: "--port ${PORT:-8080} --root ${SATUFILE_ROOT:-./data}",
      interpreter: "none",
      env: {
        NODE_ENV: "development",
        PORT: 8080,
        SATUFILE_ROOT: "./data",
        SATUFILE_ADDRESS: "0.0.0.0",
        SATUFILE_DATABASE: "./data/satufile.db",
      },
      env_production: {
        NODE_ENV: "production",
        PORT: 8080,
        SATUFILE_ROOT: "./data",
        SATUFILE_ADDRESS: "0.0.0.0",
        SATUFILE_DATABASE: "./data/satufile.db",
        SATUFILE_JWT_SECRET: "change-me-in-production-please",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      kill_timeout: 5000,
      listen_timeout: 3000,
      shutdown_with_message: true,
      out_file: "./logs/pm2.out.log",
      error_file: "./logs/pm2.err.log",
      log_file: "./logs/pm2.combined.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      kill_retry_time: 100,
    },
  ],
};
